spring:
  application:
    name: blobs-zuul
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 0.1
  zipkin:
    base-url: http://localhost:9411/
server:
  port: 10000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/